name: Setup Environment
inputs:
  CACHIX_SIGNING_KEY: # determines what node version to install
    required: true
    description: 'Cachix Signing Key'
runs:
  using: "composite"
  steps:
  
    - name: Installing Nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable

    - uses: cachix/cachix-action@v10
      with:
        name: nixos-search
        signingKey: '${{ inputs.CACHIX_SIGNING_KEY }}'

    - name: Installing jq
      shell: bash
      run: |
        nix-env -f '<nixpkgs>' -iA jq
