name: Setup Environment
inputs:
  GITHUB_TOKEN:
    required: true
    description: "GitHub access token used to prevent GitHub's rate limit for unauthenticated requests"
  CACHIX_SIGNING_KEY: # determines what node version to install
    required: true
    description: 'Cachix Signing Key'
runs:
  using: "composite"
  steps:

    - name: Installing Nix
      uses: cachix/install-nix-action@v18
      with:
        install_url: https://releases.nixos.org/nix/nix-2.13.3/install
        nix_path: nixpkgs=channel:nixpkgs-unstable
        extra_nix_config: |
          access-tokens = github.com=${{ inputs.GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v12
      with:
        name: nixos-search
        signingKey: '${{ inputs.CACHIX_SIGNING_KEY }}'

    - name: Installing jq
      shell: bash
      run: |
        nix-env -f '<nixpkgs>' -iA jq
