name: Setup Environment

runs:
  using: "composite"
  steps:
  
    - name: Installing Nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable

    - uses: cachix/cachix-action@v10
      with:
        name: nixos-search
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Installing jq
      run: |
        nix-env -f '<nixpkgs>' -iA jq
