{
  # Inputs name's should match their repository (replacing "." with "_"), sorted alphabetically
  inputs = {
    agenix.url = "github:ryantm/agenix";
    aarch64-darwin.url = "github:nix-systems/aarch64-darwin";
    aarch64-linux.url = "github:nix-systems/aarch64-linux";
    autofirma-nix.url = "github:nix-community/autofirma-nix";
    atuin.url = "github:atuinsh/atuin";
    bazel-nix.url = "github:vorburger/bazel-nix";
    bitbucket-runner-nix.url = "github:kashw2/bitbucket-runner-nix";
    chromium-pwa-wmclass-sync.url = "github:bohdantkachenko/chromium-pwa-wmclass-sync";
    current-system.url = "github:nix-systems/current-system";
    deadnix.url = "github:astro/deadnix";
    default.url = "github:nix-systems/default";
    default-darwin.url = "github:nix-systems/default-darwin";
    default-linux.url = "github:nix-systems/default-linux";
    dmake.url = "github:raboof/dmake/nix";
    embers-nix-packages.url = "git+https://codeberg.org/alch_emi/embers-nix-packages.git";
    eza.url = "github:eza-community/eza";
    # fenix.url = "github:nix-community/fenix"; # error: attribute 'outputName' missing
    fingerpaint.url = "github:Wazzaps/fingerpaint";
    flake-compat.url = "github:edolstra/flake-compat";
    flake-outputs.url = "github:nix-systems/flake-outputs";
    flake-parts.url = "github:hercules-ci/flake-parts";
    flake-utils.url = "github:numtide/flake-utils";
    flake-utils-plus.url = "github:gytis-ivaskevicius/flake-utils-plus";
    fleet.url = "github:CertainLach/fleet";
    filestash-nix.url = "github:matthewcroughan/filestash-nix";
    fw-fanctrl.url = "github:TamtamHero/fw-fanctrl/packaging/nix";
    geomyidae-flake.url = "sourcehut:~munksgaard/geomyidae-flake";
    haskell-nix.url = "github:input-output-hk/haskell.nix";
    helix.url = "github:helix-editor/helix";
    home-manager.url = "github:nix-community/home-manager";
    hydra.url = "github:NixOS/hydra";
    hyprland.url = "github:hyprwm/hyprland";
    jail-nix.url = "sourcehut:~alexdavid/jail.nix";
    jj.url = "github:jj-vcs/jj";
    kalker.url = "github:PaddiM8/kalker";
    kconfq.url = "github:synalice/kconfq";
    lightmeter.url = "github:ngi-nix/lightmeter";
    # lnbits-legend.url = "github:lnbits/lnbits-legend"; # `nix flake check` fails
    mcp-nixos.url = "github:utensils/mcp-nixos";
    micropython-builder.url = "github:jonahbron/micropython-builder";
    # multifirefox.url = "git+https://codeberg.org/wolfangaukang/multifirefox"; # wolfangaukang is no longer in 'maintainers'
    nativelink.url = "github:TraceMachina/nativelink";
    # neohtop.url = "github:hannesgith/neohtop/nixify"; # missing field 'name'
    neuropil.url = "gitlab:pi-lar/neuropil";
    nix-atlas.url = "github:dgollings/nix-atlas";
    nix-bitcoin.url = "github:fort-nix/nix-bitcoin";
    nix-cargo-integration.url = "github:yusdacra/nix-cargo-integration";
    nix-flatpak.url = "github:gmodena/nix-flatpak";
    nix-minecraft.url = "github:Infinidoge/nix-minecraft";
    nix-security.url = "github:juliosueiras-nix/nix-security";
    nix-software-center.url = "github:snowfallorg/nix-software-center";
    nix-vscode-extensions.url = "github:nix-community/nix-vscode-extensions";
    nix-waterfox.url = "github:Hythera/nix-waterfox";
    nixpkgs-esp-dev.url = "github:mirrexagon/nixpkgs-esp-dev";
    nixpkgs-ruby.url = "github:bobvanderlinden/nixpkgs-ruby";
    nixpkgs-terraform.url = "github:stackbuilders/nixpkgs-terraform";
    nixos-conf-editor.url = "github:snowfallorg/nixos-conf-editor";
    nixvim.url = "github:pta2002/nixvim";
    niri.url = "github:YaLTeR/niri";
    nosys.url = "github:divnix/nosys";
    # numen-nix.url = "github:anpandey/numen-nix"; # `nix flake check` fails
    nyx.url = "github:chaotic-cx/nyx";
    octopin.url = "github:raboof/octopin/nix";
    offen.url = "github:ngi-nix/offen";
    openpgp-ca.url = "github:ngi-nix/openpgp-ca";
    opnix.url = "github:brizzbuzz/opnix";
    PrismLauncher.url = "github:PrismLauncher/PrismLauncher";
    pyproject_nix.url = "github:pyproject-nix/pyproject.nix";
    python-trovo.url = "git+https://codeberg.org/wolfangaukang/python-trovo";
    rquickshare.url = "github:hannesgith/rquickshare/flake";
    resholve.url = "github:abathur/resholve";
    riscv64-linux.url = "github:nix-systems/riscv64-linux";
    rust-nix-templater.url = "github:yusdacra/rust-nix-templater";
    Solaar-Flake.url = "github:Svenum/Solaar-Flake";
    solc_nix.url = "github:hellwolf/solc.nix";
    sops-nix.url = "github:Mic92/sops-nix";
    std.url = "github:divnix/std";
    surrealdb.url = "github:surrealdb/surrealdb";
    sway-timetracker.url = "sourcehut:~kerstin/sway-timetracker";
    telescope.url = "github:StardustXR/telescope";
    uv2nix.url = "github:pyproject-nix/uv2nix";
    weblate.url = "github:ngi-nix/weblate";
    wrapper-manager.url = "github:viperML/wrapper-manager";
    x86_64-darwin.url = "github:nix-systems/x86_64-darwin";
    x86_64-linux.url = "github:nix-systems/x86_64-linux";
    zed.url = "github:zed-industries/zed";
  };

  outputs = _: { };
}
