[[sources]]
type = "github"
owner = "anpandey"
repo = "numen-nix"

[[sources]]
# Please open upstream issue when removing:
# https://github.com/astro/microvm.nix/issues/new
type = "github"
owner = "astro"
repo = "microvm.nix"

[[sources]]
type = "github"
owner = "atuinsh"
repo = "atuin"

[[sources]]
type = "github"
owner = "bobvanderlinden"
repo = "nixpkgs-ruby"

[[sources]]
type = "github"
owner = "brizzbuzz"
repo = "opnix"

[[sources]]
type = "github"
owner = "CertainLach"
repo = "fleet"

[[sources]]
type = "github"
owner = "chaotic-cx"
repo = "nyx"

[[sources]]
type = "github"
owner = "dgollings"
repo = "nix-atlas"

[[sources]]
type = "github"
owner = "edolstra"
repo = "flake-compat"

[[sources]]
type = "github"
owner = "eza-community"
repo = "eza"

[[sources]]
type = "github"
owner = "fort-nix"
repo = "nix-bitcoin"

[[sources]]
type = "github"
owner = "helix-editor"
repo = "helix"

[[sources]]
type = "github"
owner = "hellwolf"
repo = "solc.nix"

[[sources]]
type = "github"
owner = "hercules-ci"
repo = "flake-parts"

[[sources]]
type = "github"
owner = "hyprwm"
repo = "hyprland"

[[sources]]
type = "github"
owner = "input-output-hk"
repo = "haskell.nix"

[[sources]]
type = "github"
owner = "jj-vcs"
repo = "jj"

[[sources]]
type = "github"
owner = "jonahbron"
repo = "micropython-builder"

[[sources]]
type = "github"
owner = "juliosueiras-nix"
repo = "nix-security"

[[sources]]
type = "github"
owner = "kashw2"
repo = "bitbucket-runner-nix"

[[sources]]
type = "github"
owner = "lnbits"
repo = "lnbits-legend"

[[sources]]
type = "github"
owner = "matthewcroughan"
repo = "filestash-nix"

[[sources]]
type = "github"
owner = "Mic92"
repo = "sops-nix"

[[sources]]
type = "github"
owner = "mirrexagon"
repo = "nixpkgs-esp-dev"
