[[sources]]
type = "github"
owner = "ngi-nix"
repo = "lightmeter"

[[sources]]
type = "github"
owner = "ngi-nix"
repo = "offen"

[[sources]]
type = "github"
owner = "ngi-nix"
repo = "openpgp-ca"

[[sources]]
type = "github"
owner = "ngi-nix"
repo = "weblate"

[[sources]]
type = "github"
owner = "nix-community"
repo = "autofirma-nix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "fenix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "home-manager"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix-vscode-extensions"

[[sources]]
type = "github"
owner = "NixOS"
repo = "hydra"

[[sources]]
type = "github"
owner = "numtide"
repo = "flake-utils"

[[sources]]
type = "github"
owner = "PaddiM8"
repo = "kalker"

[[sources]]
type = "github"
owner = "PrismLauncher"
repo = "PrismLauncher"

[[source]]
type = "github"
owner = "pta2002"
repo = "nixvim"

[[sources]]
type = "github"
owner = "ryantm"
repo = "agenix"

[[sources]]
type = "github"
owner = "snowfallorg"
repo = "nixos-conf-editor"

[[sources]]
type = "github"
owner = "snowfallorg"
repo = "nix-software-center"

[[sources]]
type = "github"
owner = "stackbuilders"
repo = "nixpkgs-terraform"

[[sources]]
type = "github"
owner = "StardustXR"
repo = "telescope"

[[sources]]
type = "github"
owner = "surrealdb"
repo = "surrealdb"

[[sources]]
type = "github"
owner = "Svenum"
repo = "Solaar-Flake"

[[sources]]
type = "github"
owner = "TraceMachina"
repo = "nativelink"

[[sources]]
type = "github"
owner = "utensils"
repo = "mcp-nixos"

[[sources]]
type = "github"
owner = "Wazzaps"
repo = "fingerpaint"

[[sources]]
type = "github"
owner = "YaLTeR"
repo = "niri"

[[sources]]
type = "github"
owner = "vorburger"
repo = "bazel-nix"

[[sources]]
type = "github"
owner = "yusdacra"
repo = "nix-cargo-integration"

[[sources]]
type = "github"
owner = "yusdacra"
repo = "rust-nix-templater"

[[sources]]
type = "github"
owner = "zed-industries"
repo = "zed"
