[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "IRMAseal"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "OSX-KVM"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "anastasis"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "arpa2"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "channeler"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "coriolis"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "deltabot"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "dhcpcanon"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "elRepo.io"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "goatcounter"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "hydra-test"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "imsi-psedo"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "imsi-pseudo"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "ipfs-search"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "irmago-server"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "jitsi"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "liberate"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "libspng"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "lightmeter"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "lumosql"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "magic_rb-goatcounter"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "magic_rb-vg"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "mangaki"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "nginx-auth-a2aclr"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "nixos-modules-flake-template"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "noiseExplorer"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "ocamlPackages"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "offen"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "opaque-sphinx"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "openpgp-ca"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "packeteer"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "pcb-rnd"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "pixelfed"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "project-template"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "reowolf"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "rust-threadpool"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "scion"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "scion-path-discovery"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "searchanddisplace"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "searx"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "sonar"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "thunderbird-extensions"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "tika"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "tika-extractor"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "universal-resolver"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "valaatech_kernal"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "vita"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "vulnerablecode-flake"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "weblate"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "webshell"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "wireguard-rs"

[[sources]]
repo_type = "github"
owner = "ngi-nix"
repo = "yunohost"

