[[sources]]
repo_type = "github"
owner = "NixOS"
repo = "hydra"

[[sources]]
repo_type = "github"
owner = "NixOS"
repo = "nix"

[[sources]]
repo_type = "github"
owner = "NixOS"
repo = "nix-mode"

[[sources]]
repo_type = "github"
owner = "NixOS"
repo = "nixops"

[[sources]]
repo_type = "github"
owner = "NixOS"
repo = "nixos-channel-scripts"

[[sources]]
repo_type = "github"
owner = "NixOS"
repo = "nixos-common-styles"

[[sources]]
repo_type = "github"
owner = "NixOS"
repo = "nixos-hardware"

[[sources]]
repo_type = "github"
owner = "NixOS"
repo = "nixos-homepage"

[[sources]]
repo_type = "github"
owner = "NixOS"
repo = "nixos-planet"

[[sources]]
repo_type = "github"
owner = "NixOS"
repo = "nixos-search"

[[sources]]
repo_type = "github"
owner = "NixOS"
repo = "nixos-status"

[[sources]]
repo_type = "github"
owner = "NixOS"
repo = "nixos-summer"

[[sources]]
repo_type = "github"
owner = "NixOS"
repo = "nixpkgs"

[[sources]]
repo_type = "github"
owner = "NixOS"
repo = "nixpkgs-channels"

[[sources]]
repo_type = "github"
owner = "NixOS"
repo = "patchelf"

[[sources]]
repo_type = "github"
owner = "NixOS"
repo = "templates"

