[[sources]]
type = "git"
url = "git+https://codeberg.org/wolfangaukang/python-trovo?ref=main"

[[sources]]
type = "git"
url = "git+https://codeberg.org/wolfangaukang/multifirefox?ref=main"

[[sources]]
type = "git"
url = "git+https://github.com/hannesgith/rquickshare?ref=flake"

[[sources]]
type = "git"
url = "git+https://github.com/hannesgith/neohtop?ref=nixify"

[[sources]]
type = "git"
url = "git+https://github.com/raboof/octopin?ref=nix"

[[sources]]
type = "git"
url = "git+https://github.com/TamtamHero/fw-fanctrl?ref=packaging/nix"

[[sources]]
type = "gitlab"
owner = "pi-lar"
repo = "neuropil"

[[sources]]
type = "sourcehut"
owner = "~kerstin"
repo = "sway-timetracker"

[[sources]]
type = "sourcehut"
owner = "~munksgaard"
repo = "geomyidae-flake"
