[[sources]]
repo_type = "github"
owner = "tweag"
repo = "gomod2nix"

[[sources]]
repo_type = "github"
owner = "tweag"
repo = "jupyterWith"

[[sources]]
repo_type = "github"
owner = "tweag"
repo = "nickel"

[[sources]]
repo_type = "github"
owner = "tweag"
repo = "nix-installer-generator"

[[sources]]
repo_type = "github"
owner = "tweag"
repo = "ocaml-uri-bazel"

[[sources]]
repo_type = "github"
owner = "tweag"
repo = "okapi"

